//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agencia_Vehiculos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agencia
    {
        public int Id_agencia { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Vehiculo { get; set; }
    
        public virtual Vehiculo Vehiculo1 { get; set; }
    }
}
