//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agencia_Vehiculos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int Id_venta { get; set; }
        public Nullable<int> Vehiculo { get; set; }
        public Nullable<int> Cliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Pago { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual Vehiculo Vehiculo1 { get; set; }
    }
}
